stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to EC2"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - ssh $EC2_USER@$EC2_HOST "
      cd $DEPLOY_PATH &&
      git pull origin main &&
      docker compose down &&
      echo 'Containers stopped, waiting until build success...' &&
      docker compose build &&
      docker compose up -d &&
      docker compose exec app composer install &&
      docker compose exec app php artisan key:generate &&
      docker compose exec app php artisan migrate --seed &&
      docker compose exec app php artisan passport:client --personal --name="GitLab Personal Access Client" --no-interaction || echo "ℹ️ Personal access client may already exist." &&
      docker compose exec app php artisan storage:link &&
      docker compose exec app php artisan optimize
      "
