FROM nginx:alpine

COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY .docker/nginx/vhost_aws_fargate.conf /etc/nginx/conf.d/vhost_aws_fargate.conf
COPY .docker/nginx/vhost.conf /etc/nginx/conf.d/vhost.conf

EXPOSE 80
