server {
    listen 80;
    server_name example.com www.example.com;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html/public;



    location / {
        try_files $uri $uri/ /index.php?$args;
        gzip_static on;
    }

    client_max_body_size 3048m;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }


       # Location block for publicly accessible files in Laravel's storage.
    location /storage/ {
        # IMPORTANT: 'alias' must point to the correct physical path
        # of your public storage directory.
        alias /var/www/html/storage/app/public/;

        try_files $uri $uri/ =404;

        # Serve PDFs with a content-disposition header to display them inline.
        location ~* \.pdf$ {
            add_header Content-Disposition inline;
            add_header Access-Control-Allow-Origin *;
        }

        # CRUCIAL SECURITY MEASURE:
        # Prevents any PHP files uploaded to the storage directory from being executed.
        location ~ \.php$ {
            deny all;
        }
    }
}
